# Generated by Django 3.2.16 on 2023-03-10 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('co_id', models.IntegerField(primary_key=True, serialize=False)),
                ('ds_id', models.IntegerField()),
                ('response', models.CharField(max_length=200)),
                ('u_id', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
            options={
                'db_table': 'communication',
                'managed': False,
            },
        ),
    ]
