# Generated by Django 3.2.16 on 2023-03-10 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Friendlist',
            fields=[
                ('f_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'friendlist',
                'managed': False,
            },
        ),
    ]
